What is an ACTIVATION FUNCTION..??
ACTIVATION FUNCTION is added with every neural layers.... It determines whether the neuron
should be activated of not.. An ACTIVATION FUNCTION also convertes the output from linearity to
non-linearity from every neuron. 

If there is no ACTIVATION FUNCTION, then the neural net will only work on a those data who are separated by
linear fashion. 

I-E :- Prediction the Closing time of a company will not work if there is no ACTIVATION FUNCTION attached to the 
       neuron layer.Hence, it will behave like a simple Linear Regression Model

In [4]:
import tensorflow as tf
import numpy as np

In [87]:
W = tf.Variable(np.random.randn(2,1),dtype=np.float16)
b = tf.Variable([0.0],shape=1,dtype = np.float16)

In [88]:
W,b

(<tf.Variable 'Variable:0' shape=(2, 1) dtype=float16, numpy=
 array([[ 0.4172],
        [-1.74  ]], dtype=float16)>,
 <tf.Variable 'Variable:0' shape=(1,) dtype=float16, numpy=array([0.], dtype=float16)>)

Defining a Model without an activation funtion

In [89]:
@tf.function
def forward(X):
    output = tf.matmul(X,W)+b
    return output 

In [90]:
X = tf.convert_to_tensor(np.random.randn(1,2),dtype=np.float16)
print(X.numpy())

[[ 0.85   -0.3074]]


In [91]:
print(forward(X).numpy())

[[0.8896]]


In [92]:
out = forward(X)
print(out)

tf.Tensor([[0.8896]], shape=(1, 1), dtype=float16)


-- SIGMOID ACTIVATION FUNCTION

    RANGE (0,1)
    Used in the models where the output is in the binary form predicting whether the input is a 
    cat or a dog

In [93]:
sigmoid = tf.nn.sigmoid(out)
print(sigmoid.numpy())

[[0.7085]]


TanH or HyperBolic Tangent Function

    Range(-1,1)
    Used in the model where the input is in the form of classification
    i-e, Cat or Dog

In [94]:
tanh = tf.nn.tanh(out)

In [95]:
print(tanh.numpy())

[[0.7114]]


RELU ( Rectified Linear Unit )
    range(0, infinite(+))
    One of the most used Activation Function, If you are not sure which Activation Function you 
    should use, then go for RELU, because it is a non-satured Activation function, which means 
    it doesnot converge towards a threshold

In [96]:
relu = tf.nn.relu(out)
print(relu.numpy())

[[0.8896]]


Softmax Activation Function 
    range (0,1)
    It returns a vector of probabilities depending on the number of classes, the total sum of the 
    output vector will add upto 1. It is used in the models there is multi-class classification

In [97]:
softmax = tf.nn.softmax(out)
print(softmax.numpy())

[[1.]]
